version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./reddit_comments.db:/usr/src/app/reddit_comments.db
    ports:
      - "8282:8282"
    command: flask run --host=0.0.0.0 --port=8282

  scheduler:
    build: .
    volumes:
      - ./reddit_comments.db:/usr/src/app/reddit_comments.db
    command: sh -c "while true; do python main.py; sleep 60; done"
