version: '3.8'

networks:
  wp:
    external: true

services:
  app:
    build: .
    volumes:
      - ./reddit_comments.db:/usr/src/app/reddit_comments.db
    ports:
      - "8282:8282"
    command: python app.py
    networks:
      - reddit_wp
  scheduler:
    build: .
    volumes:
      - ./reddit_comments.db:/usr/src/app/reddit_comments.db
    command: sh -c "while true; do python main.py; sleep 60; done"
    networks:
      - reddit_wp
