version: '3.8'

networks:
  wp:
    driver: bridge

services:
  scheduler:
    build: .
    volumes:
      - ./data:/usr/src/app/data
    command: sh -c "while true; do python main.py; sleep 60; done"
    networks:
      - wp
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8443:443"
    networks:
      - wp
volumes:
  app:
  scheduler:
